# pyproject.toml
[project]
name = "my-static-blog"
version = "0.1.0"
dependencies = [
    "Jinja2",
    "markdown",
    "python-frontmatter",
    "beautifulsoup4",
    "Pygments",
    "pymdown-extensions",
]

[project.scripts]
build = "src.main:run"
